name: Deploy Backend to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      - name: Deploy na Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd ~/DSM-G09-PI4-2025-2
            git pull origin main

            cd backend
            npm install --omit=dev

            pm2 restart ouviot-backend || pm2 start server.js --name ouviot-backend
            pm2 save
          EOF
